### ISSUE TITLE
Call the sampler with manual handwritten gradient

### ISSUE THREAD

**Issue by wupeifan** [tpapp/DynamicHMC.jl#111]
Hi Tamas,

I am trying to run the NUTS sampler without automatic differentiation as I have some gradient function handwritten. I was wondering whether there are any ways to call the sampler (such as `mcmc_with_warmup` without 1. automatic differentiation of the log-likelihood; 2.  TransformVariables? 
I understand that both of the features are very convenient, but as I can explicitly write out the gradient I just want to call the NUTS sampler in a "raw" way. Are there any ways for me to do so? I haven't managed to Google out an example (either on the documentation or on discourse)
Thank you!

Peifan

**Comment by tpapp** [comment]
Sorry I missed this issue. See the docs at

https://tamaspapp.eu/LogDensityProblems.jl/dev/#Manually-calculated-derivatives-1

**Comment by wupeifan** [comment]
Thanks a lot! I didn't know it was in another documentation.
