### ISSUE TITLE
v1.0.5 bounds and Optim bounds

### ISSUE THREAD

**Issue by karajan9** [tpapp/DynamicHMC.jl#128]
Alright, I'll jump right in and violate the very first rule and talk about old versions.
Version `1.0.5` has the bound `LogDensityProblems = "≥ 0.8.0"`, however, it also uses `ValueGradient` and consequently breaks with the automatically installed `LogDensityProblems 0.9.0`.

I think I got version `1.0.5` because Pkg preferred it over downgrading `Optim` from `0.21` to `0.20` so an intermediate fix might be to adjust that bound (which `1.0.5` doesn't have in the first place), assuming that doesn't break anything.

**Comment by tpapp** [comment]
I am closing this because it is fixed on recent versions. Apologies if old versions break for you (because they are still in the registry). I recommend using the latest versions.
