### ISSUE TITLE
Progress report that is a progress bar using `ProgressMeter.jl`

### ISSUE THREAD

**Issue by DilumAluthge** [tpapp/DynamicHMC.jl#135]
If I understand correctly, currently there are two progress reporters available in DynamicHMC.jl:

| Progress reporter | Outputs | 
| ------------------ | -------- |
| `NoProgressReport` | no output | 
| `LogProgressReport` | prints information every `X` seconds using the `@info` macro |

Would it be possible to add a third progress reporter that is just a simple progress bar using [`ProgressMeter.jl`](https://github.com/timholy/ProgressMeter.jl)?

This would require adding `ProgressMeter.jl` as a dependency. If you are fine with that @tpapp, I can work on making a PR.

I'd like to use this in the [SossMLJ.jl](https://github.com/cscherrer/SossMLJ.jl) package that @cscherrer and I are working on.

**Comment by tpapp** [comment]
Yes, I am fine with this, please go ahead.
