### ISSUE TITLE
Warning: (t::AbstractTransform)(x) is deprecated, use transform(t, x) instead

### ISSUE THREAD

**Issue by goedman** [tpapp/DynamicHMC.jl#148]
Hi Tamas,

As I'm slowly trying to think about the `project` StatisticalRethinkingDhmc, I ran the tests for `StatisticalRethinking/DynamicHMCModels.jl` once more and get below warnings.

Most models show these warnings. The results look fine.

Is this something on my side?

It happens on Julia 1.5, 1.6 and nightly on both DynamicHMC v2.2 and 3.0.

Thanks,
Rob

```
* ../scripts/02/m2.1d.jl *

┌ Warning: (t::AbstractTransform)(x) is deprecated, use transform(t, x) instead
│   caller = _broadcast_getindex_evalf at broadcast.jl:648 [inlined]
└ @ Core ./broadcast.jl:648

(p = 0.617 ± 0.087,)

1.1982911965439602
Hamiltonian Monte Carlo sample of length 1000
  acceptance rate mean: 0.93, 5/25/50/75/95%: 0.72 0.91 0.97 1.0 1.0
  termination: divergence => 0%, max_depth => 0%, turning => 100%
  depth: 0 => 0%, 1 => 62%, 2 => 38%

 * ../scripts/02/m2.1d.jl completed

```

**Comment by tpapp** [comment]
> Is this something on my side?

No, I deprecated the `t(x)` syntax in `TransformVariables`, replace with `transform(t, x)`.
