### ISSUE TITLE
GitHub Discussions

### ISSUE THREAD

**Issue by pitmonticone** [tpapp/DynamicHMC.jl#151]
Hi, would you mind enabling the [GitHub Discussions](https://docs.github.com/en/discussions/quickstart)? 

Thank you very much for the development and maintenance of this great package!

**Comment by tpapp** [comment]
I am happy to hear that you find it useful. I have enabled Github Discussions (I think), if it does not work let me know.

That said, you can also ping me on Discourse (`@Tamas_Papp`) with questions.
