### ISSUE TITLE
tag new release

### ISSUE THREAD

**Issue by tpapp** [tpapp/DynamicHMC.jl#18]
Conditional on:

- [x] https://github.com/JuliaLang/METADATA.jl/pull/17307 being merged

TODO:

- [ ] remove `1.0` from `allow_failures`
- [ ] update examples repo

**Comment by Vaibhavdixit02** [comment]
Hey @tpapp can you let me know the timeline for this next release? I would also be interested in contributing if you think there is something I could help out with?

**Comment by tpapp** [comment]
Technically, once I update the examples repo I could release; but I wanted to do a bit more benchmarking and optimization on TransformVariables.

You can help by testing early, I will follow up in this topic. The timeline is a few weeks.

**Comment by Vaibhavdixit02** [comment]
Okay cool. 🙂

**Comment by tpapp** [comment]
@Vaibhavdixit02: I updated the [examples repo](https://github.com/tpapp/DynamicHMCExamples.jl/), now things are working more or less. Testing would be appreciated.

Also, if you have a simple model in mind you would like to contribute to the examples repo, please open a PR and I will help out (if you need it).

**Comment by tpapp** [comment]
This is obsoleted by releasing 1.0.
