### ISSUE TITLE
What is a "step"?

### ISSUE THREAD

**Issue by simonbyrne** [tpapp/DynamicHMC.jl#36]
The sampler prints out info like "0.19 s/step". I assume that's per MH step, not per leapfrog step? It would be useful to be more precise.

**Comment by tpapp** [comment]
Good question. It is the time spent building each tree (there are no MH steps in HMC). Perhaps it would be more informative to display 

- avg time / leapfrog step
- avg tree depth or size
- avg time / tree

This should be addressed by #30.

**Comment by tpapp** [comment]
I clarified this in the docs after the API reorg, feeling that this is the best I can do without being too verbose. If you have a suggestion, please feel free to reopen.
