### ISSUE TITLE
Further on my previous request (Request for help #12 in DynamicHMCExamples)

### ISSUE THREAD

**Issue by goedman** [tpapp/DynamicHMC.jl#42]
Hi Tamas,

I've tried to simplify above mentioned request for help a bit further to make a as close as possible to a MWE. The example needs the chimpanzees.TXT data (it is a csv file but GitHub doesn't support that) and below script. The expected results are in the variable `rethinking`. At the end of the script I print off the DynamicHMC values. The alpha values seem ok, bp and bpC are consistently off.

[chimpanzees.TXT](https://github.com/tpapp/DynamicHMC.jl/files/3023496/chimpanzees.TXT)

```
using CSV, DataFrames, Random, Distributions, LinearAlgebra
using StatsBase, StatsFuns
using DynamicHMC, TransformVariables, LogDensityProblems
using MCMCDiagnostics, LinearAlgebra, Statistics
using Parameters, ForwardDiff

Random.seed!(12345)

# Change to a local directory where chimpanzees.txt is stored

ProjDir = @__DIR__
cd(ProjDir)

# Read in chimpanzees and convert columns to Float68
# Same result is obtained if left as Int64.

d = CSV.read("chimpanzees.txt", delim=',');
df = convert(DataFrame, d);
df[:pulled_left] = convert(Array{Float64}, df[:pulled_left])
df[:prosoc_left] = convert(Array{Float64}, df[:prosoc_left])
df[:condition] = convert(Array{Float64}, df[:condition])
df[:actor] = convert(Array{Int64}, df[:actor])

struct m_10_04d_model{TY <: AbstractVector, TX <: AbstractMatrix,
  TA <: AbstractVector}
    "Observations."
    y::TY
    "Covariates"
    X::TX
    "Actors"
    A::TA
    "Number of observations"
    N::Int
    "Number of unique actors"
    N_actors::Int
end

# Make the type callable with the parameters *as a single argument*.

function (problem::m_10_04d_model)(θ)
    @unpack y, X, A, N, N_actors = problem
    @unpack β, α = θ
    ll = 0.0
    ll += sum(logpdf.(Normal(0, 10), β)) # bp & bpC
    ll += sum(logpdf.(Normal(0, 10), α)) # alpha[1:7]
    ll += sum(
      (loglikelihood(Binomial(1, logistic(α[A[i]] + dot(X[i, :], β))), [y[i]]) for i in 1:N)
    )
    ll
end

# Instantiate the model with data and inits.

N = size(df, 1)
N_actors = length(unique(df[:actor]))
X = hcat(ones(Int64, N), df[:prosoc_left] .* df[:condition]);
A = df[:actor]
y = df[:pulled_left]
p = m_10_04d_model(y, X, A, N, N_actors);
θ = (β = [1.0, 0.0], α = [-1.0, 10.0, -1.0, -1.0, -1.0, 0.0, 2.0])
p(θ)

problem_transformation(p::m_10_04d_model) =
    as( (β = as(Array, size(p.X, 2)), α = as(Array, p.N_actors), ) )

P = TransformedLogDensity(problem_transformation(p), p)
∇P = LogDensityRejectErrors(ADgradient(:ForwardDiff, P));
#∇P = ADgradient(:ForwardDiff, P);
#LogDensityProblems.stresstest(P)

chain, NUTS_tuned = NUTS_init_tune_mcmc(∇P, 1000);
posterior = TransformVariables.transform.(Ref(problem_transformation(p)), get_position.(chain));
posterior_β = mean(first, posterior)
posterior_α = mean(last, posterior)

# Result CmdStan

rethinking = "
Iterations = 1:1000
Thinning interval = 1
Chains = 1,2,3,4
Samples per chain = 1000

Empirical Posterior Estimates:
        Mean        SD       Naive SE       MCSE      ESS
a.1 -0.74503184 0.26613979 0.0042080396 0.0060183398 1000
a.2 10.77955494 5.32538998 0.0842018089 0.1269148045 1000
a.3 -1.04982353 0.28535997 0.0045119373 0.0049074219 1000
a.4 -1.04898135 0.28129307 0.0044476339 0.0056325117 1000
a.5 -0.74390933 0.26949936 0.0042611590 0.0052178124 1000
a.6  0.21599365 0.26307574 0.0041595927 0.0045153523 1000
a.7  1.81090866 0.39318577 0.0062168129 0.0071483527 1000

 bp  0.83979926 0.26284676 0.0041559722 0.0059795826 1000
bpC -0.12913322 0.29935741 0.0047332562 0.0049519863 1000
";

# Means of draws

[posterior_β, posterior_α]
```

**Comment by tpapp** [comment]
Thanks, this should help a lot. Do you by any change have this coded in Stan, so that I could compare adaptation?

**Comment by goedman** [comment]
Yip, it baffles me this is the only model that is not spot on. This is the Stan version I have been using:

```
m_10_04 = "
data{
    int N;
    int N_actors;
    int pulled_left[N];
    int prosoc_left[N];
    int condition[N];
    int actor[N];
}
parameters{
    vector[N_actors] a;
    real bp;
    real bpC;
}
model{
    vector[N] p;
    bpC ~ normal( 0 , 10 );
    bp ~ normal( 0 , 10 );
    a ~ normal( 0 , 10 );
    for ( i in 1:504 ) {
        p[i] = a[actor[i]] + (bp + bpC * condition[i]) * prosoc_left[i];
        p[i] = inv_logit(p[i]);
    }
    pulled_left ~ binomial( 1 , p );
}
";
```
The result in StanModels.jl is documented at [m10.04s.jl](https://statisticalrethinkingjulia.github.io/StanModels.jl/latest/10/m10.04s) with also a link back to Github on that page. I know you use StanDump, but on this page is how I set up the data.

**Comment by goedman** [comment]
If that is easier, I have also occasionally tested a logpdf version [m10.04sl.jl](https://github.com/StatisticalRethinkingJulia/StanModels.jl/blob/master/scripts/10/m10.04sl.jl).

**Comment by tpapp** [comment]
I have reproduced and tested this example against Stan using `master` for DynamicHMC (the sampling kernel is now basically done, the API is still WIP). I can provide the code if you prefer. I see the following differences:

1. DynamicHMC adapts to a stepsize of 0.51, Stan 0.26
2. tails are a bit fatter for `bp` in DynamicHMC, the rest of the variables are spot on,
3. DynamicHMC has smaller trees (because of the larger stepsize).

Was this the original issue, or was there something else?

I am not convinced that Stan is actually adapting well in this example, because all those small stepsizes lead to larger trees and super-high acceptance rates.

**Comment by goedman** [comment]
Hi Tamas, thank you for looking into this. Would you mind providing me with the code? Would love to see your new results. In the meantime I'll close this issue. Thanks again!

**Comment by tpapp** [comment]
I am reworking the API this week, your code will be the first non-trivial example :smile: Will make it public, feel free to ask me again if I am late.

BTW, what's the license of the chimpanzees data? Can I just copy it?

**Comment by goedman** [comment]
I will confirm that with Richard McElreath and get back to you.

**Comment by goedman** [comment]
Hi Tamas,

Please find Richard's response on my (and your) request below. Interesting that he was aware of this work (maybe via Richard Torkar who helped with the Turing models) and has some interest in Julia as well. If I'm correct, Prague & Leipzig are not that far from another :-)

Best,
Rob

```
Begin forwarded message:

From: Richard McElreath <richard_mcelreath@eva.mpg.de>
Subject: Re: Question on license for re-use of data files.
Date: July 30, 2019 at 02:03:19 MDT
To: "Rob J. Goedman" <goedman@icloud.com>

Hi, Rob.

I licensed the package under GPL 3+, which I believe allows you to do whatever you want. I certainly don't see any issues with repackaging the data examples.

Really super work, by the way. I am trying to move my workflow to Julia. Collaboration keeps me tied to R, however. 

Anyway, if you need anything more, please just ask.

Cheers,
Richard



On Mon, Jul 29, 2019 at 9:09 PM Rob J. Goedman <goedman@icloud.com> wrote:
First of all, thank you for a great book, R package and on-line lectures!

My name is Rob Goedman and I maintain a Julia (language) version of the cmdstan interface ( https://github.com/StanJulia ). As such I am part of the Stan development team.

Since about a year I have explored (and released) some early versions of a Julia version of StatisticalRethinking ( https://github.com/StatisticalRethinkingJulia ) and example implementations of most models in 3 available mcmc implementations in Julia  (the above mentioned StanJulia, DynamicHMC.jl [ https://github.com/tpapp/DynamicHMC.jl ] and Turing.jl [ https://github.com/TuringLang/AdvancedHMC.jl ]).

Currently I am working on a first official release (v”1.0.0”) and wanted to check in if there are restrictions on re-use of the data files provided in the R package `rethinking` for that purpose (as Julia is mostly released under an MIT-license).

The question was also triggered by the fact that one of the models (m11.4 in the 2nd edition) results in different tuning results in cmdstan and in DynamicHMC and the author of that package has asked if he could use the data for that model for his test case.

Best,
Rob J Goedman
goedman@icloud.com

```

**Comment by tpapp** [comment]
Hi Rob, thanks for asking Richard. Unfortunately, I don't think that the GPL would allow copying stuff to a package with MIT license (that applies to DynamicHMC, and also StatisticalRethinking).

Perhaps consider opening an issue at https://github.com/StatisticalRethinkingJulia/StatisticalRethinking.jl to see if the license could be changed at least for the data.

**Comment by goedman** [comment]
Hi Tamas,

In the end I decided to update the license for StatisticalRethinking to GPL v3. It might have been possible in this case to use a mixed license but as I consider this an educational package keeping it simple is more important. I'll likely do the same for the ...Models.jl packages as I update them over the next few weeks.

If that is not acceptable to you for DynamicHMC, I'm happy to include an extended example, including relevant diagnostics, in StatisticalRethinking.jl and/or DynamicHMCModels.jl.

In MCMCBenchmarks.jl, which will remain MIT licensed, I'm planning to include a simulation of that example to try how sensitive the results are to different input data.

Best,
Rob

**Comment by tpapp** [comment]
Sorry, I cannot use GPL-licensed stuff in my packages. But I can of course make the script available for you and you can use it in your own package, I think that is fine.
