### ISSUE TITLE
Registrator release

### ISSUE THREAD

**Issue by andreasnoack** [tpapp/DynamicHMC.jl#46]
The current version has capped `TransformVariables` at 0.2 because of how the conversion script from METADATA works so it would be great with a new release that allows for `TransformVariables` >= 0.3

**Comment by StefanKarpinski** [comment]
I can make a PR like https://github.com/JuliaRegistries/General/pull/256 to fix this. What should I do? Change the upper bound on all packages that depend on DynamicHMC from `0.2` to `0.*`?

**Comment by tpapp** [comment]
I think rather for all packages that depend on TransformVariables, to `0.*`.

**Comment by StefanKarpinski** [comment]
So I see the following dependencies on `TransformVariables`:
```
D/DiffEqBayes/Compat.toml
45:TransformVariables = "0-0.2"

D/DynamicHMC/Compat.toml
19:TransformVariables = "0-0.2"

D/DynamicHMCModels/Compat.toml
22:TransformVariables = "0-0.2"

L/LogDensityProblems/Compat.toml
["0-0.8.0"]
9:TransformVariables = "0-0.2"
--
21-["0.8.1"]
22:TransformVariables = "0.2"
--
24-["0.8.2-0"]
25:TransformVariables = "0.2-0"

S/StatisticalRethinking/Compat.toml
47:TransformVariables = "0-0.2"
```
Presumably all the `0-0.2` ones should be changed to `0` and the `0.2-0` one should be left alone. What about the `0.2` compat entry? Should that be changed to `0.2-0` or left alone? In other words, do you want LogDensityProblems 0.8.1 capped at 0.2 or uncapped and free to use 0.3 and higher?

**Comment by tpapp** [comment]
Sorry, I don't understand what `0.2-0` means in this context.

But it is very likely that 0.3 is a drop-in replacement for 0.2 for most people, so anyone who used 0.2 should be fine with 0.3.

That said, to be conservative, we can just fix it for my own packages, DynamicHMC and LogDensityProblems. There, 0.* would be ideal.

**Comment by StefanKarpinski** [comment]
`0.2-0` means that `LogDensityProblems` is compatible with an `TransformVariables` version in `[0.2.0, 1.0.0)`.

**Comment by StefanKarpinski** [comment]
PR created: https://github.com/JuliaRegistries/General/pull/265.

**Comment by StefanKarpinski** [comment]
I didn't change anything for LogDensityProblems because it was unclear but that's also your package so it seems like you could say whether the bounds should be adjusted or not there.

**Comment by tpapp** [comment]
Closed by https://github.com/JuliaRegistries/General/pull/265/
