### ISSUE TITLE
New Test Case

### ISSUE THREAD

**Issue by itsdfish** [tpapp/DynamicHMC.jl#49]
Hi Tamas-

I am following up with our discussion on [discourse](https://discourse.julialang.org/t/dynamichmc-reached-maximum-number-of-iterations/24721/2). I believe you wanted to use the LBA code as a test for your package. That is fine with me. Performing parameter estimation on the LBA is difficult due to the intercorrelations among parameters. So it makes a great test case. 

The code can be found [here](https://github.com/StatisticalRethinkingJulia/MCMCBenchmarks.jl/blob/master/Examples/LBA/LBA_dHMC.jl) and uncommenting line 176 will produce the maximum iteration error.

**Comment by itsdfish** [comment]
Sorry. I didn't realize Rob opened and closed a related issue. In either case, please feel free to use the code for testing.

**Comment by tpapp** [comment]
I appreciate that you opened this issue, thanks.
