### ISSUE TITLE
Tag?

### ISSUE THREAD

**Issue by ChrisRackauckas** [tpapp/DynamicHMC.jl#5]
Do you think this library is ready? We merged the DiffEqBayes.jl code. I will put it as an optional dependency for now via Requires but if you think this is ready then please tag. Thanks!

**Comment by tpapp** [comment]
Happy to tag (especially since a reorganization is coming up), do you also need it registered?

**Comment by ChrisRackauckas** [comment]
Yup, it would be nice!

**Comment by ChrisRackauckas** [comment]
Looks like we need ContinuousTransformations.jl and DiffWrappers.jl as well (MCMCDiagnostics.jl looks like it's already registered).

**Comment by tpapp** [comment]
Will do all of them today.

**Comment by tpapp** [comment]
Just tagged all 3, attobot should take care of the rest. Please reopen if I can help with anything else.
