### ISSUE TITLE
Option to increase the maximum iterations allowed. 

### ISSUE THREAD

**Issue by Vaibhavdixit02** [tpapp/DynamicHMC.jl#6]
Is there some way to increase the maximum iterations being passed? https://github.com/tpapp/DynamicHMC.jl/blob/4b7cc864fd3f7faf7372f0bd9132519cf1b5ae7b/src/DynamicHMC.jl#L255 If there isn't will be possible to add it? It will be useful in cases such as parameter estimation of Lorenz Equation (DiffEqBayes.jl) using DynamicHMC.jl as the backend.

**Comment by tpapp** [comment]
I am not sure I understand the question, but that's what the `maxiter_` variables do. However, that is unlikely to help since this is already a lot on a log scale. If you need more, it is possible that you are not starting from a good initial point. Please link an example.

**Comment by tpapp** [comment]
That's a very difficult problem, I doubt it can be estimated directly. From the plots Stan has truly horrible mixing, and that is not surprising. Your problem may be numerical and fundamental at the same time: the likelihood has very sharp peaks, and the sampler is maladapted to it. I don't think these methods can cope with it, I would just use indirect inference on some features of the data.

**Comment by Vaibhavdixit02** [comment]
I will take your suggestion into consideration. Thank you for the in depth explanation!

**Comment by tpapp** [comment]
Also consider introducing a stochastic (unobserved) state, making the likelihood less brittle.

(If that is OK, I will close the issue, feel free to contant me using the `@` feature in any discussion on Github or Discourse if you need help).
