### ISSUE TITLE
Issue with gaussian process model

### ISSUE THREAD

**Issue by bratslavia** [tpapp/DynamicHMC.jl#7]
This is probably an issue with ForwardDiff and how I'm writing my code, but on the off chance... 

I am running into an issue that the kernels of GPs I try to estimate are always triggering an error when it comes time to estimate using the NUTS sampling function. Specifically, the covariance matrix fails during a cholesky decomposition, sometimes with the error that it is not PD. I have tested the same functions for constructing the kernels outside of DHMC/ForwardDiff, and they work fine. I thought this might be an issue others have run into.

I've tried to provide a MWE below:

``    
    using Parameters, DynamicHMC, ContinuousTransformations, DiffWrappers, MCMCDiagnostics, CSV, DataFrames, Distributions
    
    function sq_distance(X)
        N = size(X, 1)
        dist_matrix = Array{eltype(X)}(N, N)
        
        for j in 1:N
            for i in 1:N
                dist_matrix[i, j] = (X[i] - X[j])^2
            end
        end
        
        return dist_matrix
    end

    struct GP
        X::Array{Float64, 1}
    end

    function (m::GP)(theta)
        @unpack X = m
        N = size(X, 1)
        llpost = 0.0
        signal, = theta[1]
        length, = theta[2]
        time_hat = theta[3]
        
        for i in 1:3
            all(isfinite.(theta[i])) || return -Inf
        end
        
        dist_all = sq_distance(time_hat)
        K = (signal^2) * exp.(-0.5 * dist_all/(length^2)) + 0.000001*I
        
        llpost += logpdf(MvNormal(zeros(size(K, 1)), K), X)
        
        return llpost
    end
    
    dat1 = randn(30)
    gp_model = GP(dat1)
    
    tt = TransformationTuple(bridge(ℝ, ℝ⁺), bridge(ℝ, ℝ⁺), ArrayTransformation(bridge(ℝ, ℝ), size(dat1, 1)))
    m_trans = TransformLogLikelihood(gp_model, tt)
    m_trans_g = ForwardGradientWrapper(m_trans, randn(length(m_trans)))
    m1 = m_trans(randn(length(m_trans)))
    m2 = m_trans_g(zeros(length(m_trans_g)))
    
    sample, NUTS_tuned = NUTS_init_tune_mcmc(m_trans_g, length(m_trans_g), 5000)
``

It always fails when it tries to apply chol() to the covariance matrix during sampling, although it works fine when I am just handling the transformed loglikelihood function by itself.

**Comment by tpapp** [comment]
I took the liberty of compacting your code a bit (please check that it is equivalent), and added some print statements:
```julia
using Parameters, DynamicHMC, ContinuousTransformations, DiffWrappers,
    MCMCDiagnostics, CSV, DataFrames, Distributions

sq_distance2(X) = Symmetric(abs2.(X .- X'))

calculateK(dist_all, signal, ℓ) = (signal^2) * exp.(-0.5 * dist_all./(ℓ^2)) + 0.000001*I

struct GP
    X::Array{Float64, 1}
end

function (m::GP)(theta)
    @unpack X = m
    N = size(X, 1)
    signal, ℓ, time_hat = theta

    for i in 1:3
        all(isfinite.(theta[i])) || return -Inf
    end

    dist_all = sq_distance2(time_hat)
    K = calculateK(dist_all, signal, ℓ)
    try
        logpdf(MvNormal(K), X)
    catch e
        println("******** signal:")
        println(signal)
        println("******** ℓ:")
        println(ℓ)
        println("******** singular values of K:")
        println(svd(ForwardDiff.value.(K))[2])
        error("stopped")
    end
end
```
Note how you can

1. break up calculations into functions (this is idiomatic style for Julia),

2. use broadcasting.

This stops with
```julia
******** signal:
Dual{ForwardDiff.Tag{ContinuousTransformations.TransformLogLikelihood{GP,ContinuousTransformations.TransformationTuple{Tuple{ContinuousTransformations.ComposedTransformation{ContinuousTransformations.Affine{Float64},ContinuousTransformations.Exp},ContinuousTransformations.ComposedTransformation{ContinuousTransformations.Affine{Float64},ContinuousTransformations.Exp},ContinuousTransformations.ArrayTransformation{ContinuousTransformations.Affine{Int64},(30,)}}}},Float64}}(6.297090670345185e140,6.297090670345185e140,0.0,0.0,0.0,0.0,0.0,0.0,0.0)
******** ℓ:
Dual{ForwardDiff.Tag{ContinuousTransformations.TransformLogLikelihood{GP,ContinuousTransformations.TransformationTuple{Tuple{ContinuousTransformations.ComposedTransformation{ContinuousTransformations.Affine{Float64},ContinuousTransformations.Exp},ContinuousTransformations.ComposedTransformation{ContinuousTransformations.Affine{Float64},ContinuousTransformations.Exp},ContinuousTransformations.ArrayTransformation{ContinuousTransformations.Affine{Int64},(30,)}}}},Float64}}(0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0)
******** singular values of K:
[NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN]
ERROR: stopped
```
I think this is coming from your `length` (not a good choice BTW, since it shadows `Base.length` in the scope of the function), which is my `ℓ`, being `0.0`, so you get `NaN`s from `0/0`. This can easily happen during the initial stepsize calibration for a small raw value which is passed to `exp`. 

I would suggest the following:

1. find a mode with [Optim.jl](https://github.com/JuliaNLSolvers/Optim.jl), or [BlackBoxOptim.jl](https://github.com/robertfeldt/BlackBoxOptim.jl) for nasty problems, and start from there,

2. in the likelihood calculation, check `K` with `any(K, isnan)` and return `-Inf` in case it is wrong,

In any case, I should add starting from the mode in the manual and the examples. Starting  from arbitrary values breaks down very quickly (this is to be expected).

Hope this helps, happy to help more.

**Comment by bratslavia** [comment]
Just wanted to let you know that the check for K (combined with slightly better starting values) seems to have done the trick. (In my original code, I called "length" something else, but I think your use of a Symmetric matrix helped matters.) Thanks!

BTW, do you have a sense of how well/poorly this algorithm scales with the number of parameters? Some of my models have several hundred parameters; for those, the initialization phase takes.... well, I haven't actually seen it finish yet, ha ha. :)

**Comment by tpapp** [comment]
There are some theoretical results about HMC for some distributions which suggest that time/effective sample scales as `O(n^a)` with `a=5/4`, but NUTS2 is different so I don't think there are general guidelines. For some simple models, I found a roughly linear relationship (eg `a` between `1` and `1.5`).

BTW, can I close the issue?

**Comment by bratslavia** [comment]
Yep, please close, and thanks for the help.
