### ISSUE TITLE
Add mean tree depth to NUTS_tuned

### ISSUE THREAD

**Issue by itsdfish** [tpapp/DynamicHMC.jl#73]
Hi Tamas-

I am using DynamicHMC v1.0.6 and would like to report mean tree depth for MCMCBenchmarks.jl. As far as I can tell, NUTS_tuned only reports the maximum tree depth. Would it be possible to add mean tree depth to NUTS_tuned? Thanks.

**Comment by tpapp** [comment]
The `.depth` field of the stats for each tree should contain this information. The 2.0 API (cf #69) should make this more explicit,
```julia
results = mcmc_with_warmup(rng, p, 1000)
mean(s -> s.depth, results.tree_statistics)
```
should do what you want. Cf [`TreeStatisticsNUTS`](https://github.com/tpapp/DynamicHMC.jl/blob/eb2c02e71c2ce38757e2eb1c6ceec6164b58eb46/src/NUTS.jl#L183) and how [`DynamicHMC.Diagnostics.summarize_tree_statistics`](https://github.com/tpapp/DynamicHMC.jl/blob/eb2c02e71c2ce38757e2eb1c6ceec6164b58eb46/src/diagnostics.jl#L99) extracts the depth information.

This is all on `master`, which is released soon. If you want to stick with 1.0.6 for now, the same information is in `chain` in
```julia
chain, _ = NUTS_init_tune_mcmc(...)
```

**Comment by itsdfish** [comment]
Thank you. Sorry for the false alarm.

**Comment by tpapp** [comment]
No worries. It is totally fine to ask support questions in issues and I am happy to help.
