### ISSUE TITLE
don't use sample as a global

### ISSUE THREAD

**Issue by tpapp** [tpapp/DynamicHMC.jl#9]
Eg in examples and docstrings. Conflicts with `StatsBase.sample`.

**Comment by tpapp** [comment]
possible alternatives:

1. `chain` (used by [Klara.jl](https://github.com/JuliaStats/Klara.jl)),
2. `samples` (simply the plural),
3. `sim` (used by [Mamba.jl](https://github.com/brian-j-smith/Mamba.jl))

**Comment by gabrielgellner** [comment]
I have been using `samp` if avoiding overlap with `Klara.jl` is wanted. Using `samples` feels a bit to similar to what you are trying to avoid shadowing :)

**Comment by tpapp** [comment]
I think I will go with `chain` when I revamp the docs (soon).

**Comment by tpapp** [comment]
Closed by #44, which uses a different API.
