### ISSUE TITLE
heavy dependencies for initial optimization

### ISSUE THREAD

**Issue by tpapp** [tpapp/DynamicHMC.jl#91]
Optim.jl, which is used in finding the initial local optimum, is responsible about 10-15 of the dependencies in the manifest.

Given that we just need *a* solver that gets *close* to a local optimum, is there a more streamlined solution?

**Comment by tpapp** [comment]
@oschulz: made an issue for your concern here:
https://discourse.julialang.org/t/ann-dynamichmc-2-0/28314/26

**Comment by oschulz** [comment]
Thanks! I understand that it may not be easy to make things lighter ...
